site_name: PSP Dev Notes
theme:
  name: material
nav:
  - Home: 'index.md'
  - 'What are we building?': 'buildtarget.md'
  - 'Setting up the environment': 'environment.md'
  - 'What is in the PSPSDK?': 'pspdevdir.md'
  - 'Common File Formats': 'format.md'
  - 'Build Process': 'makefilesample.md'
  - 'Hello World': 'helloworld.md'
  - Commandline Tools: 'pspdevdir.md'
  - Third Party Libraries: 'sdl.md'
  - Resident / Stub Libraries: 
    - Export & Import functions: 'stublibs.md'
    - PRX File Structure: 'prxfilestruct.md'
    - Reverse the PRX File: 
      - PRX 2 STUB: 'prx2stub.md'
      - Disasm: 'assembly.md'
  - Device Capability:
    - Display: ''
    - Utility: 
      - Dialog: ''
      - OSK: ''
      - Network: 'webrequest.md'
      - Decode: 'videoplayback.md'
      - I/O: ''
      - Timer: 'time.md'
    - VFPU: ''
    - Media Engine: 'mediaengine.md'
  - CMake: 'cmake.md'
  - Debug: 'debug.md'
  - Release: 'release.md'
  - CI / CD: 'githubactions.md'
  - Patch: 
    - 'patch.md'
    - 'patchexe.md'
    - 'cwcheat.md'
  - Recent Projects: 'recentprojects.md'
  - Offical SDK: 'sdks.md'
    
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



